language: go

sudo: false

go:
  - 1.6
  - tip

addons:
  apt:
    packages:
      - libglib2.0-dev
      - libvirt-dev
      - pkg-config

install:
  - ./autogen.sh
  - ./configure

script:
  - go fmt $(go list ./... | grep -v /vendor/)
  - make check
