language: go

sudo: required
services: docker

go:
  - 1.6
  - tip

addons:
  apt:
    packages:
      - libglib2.0-dev
      - libvirt-dev
      - pkg-config

install: ./autogen.sh
script:
  - go fmt $(go list ./... | grep -v /vendor/)
  - ls -l /boot
  - ls -l /lib/modules
  - docker ps
